### ISSUE TITLE
Configuration page needs option to switch between TOR and .local 

### ISSUE THREAD

**Issue by JesseMarkowitz** [chrisguida/cryptpad-wrapper#1]
In the current setup it is not possible to support both TOR and .local clients accessing at the same time.  We need to allow the testers to switch between the two modes so they can test each independently.

**Comment by chrisguida** [comment]
Complete as of https://github.com/chrisguida/cryptpad-wrapper/commit/01f17e87b7527c6393aaf7f443392c1f74f2eb96#diff-d281556d8b6d8db507c837ceb687972c21fca88055be42e7a0d99e937b9b643fR22

Next step is to add simultaneous tor/lan access
