### ISSUE TITLE
Donate doesn't work

### ISSUE THREAD

**Issue by JesseMarkowitz** [chrisguida/cryptpad-wrapper#10]
Currently Donate brings up a modal dialog that says: 
Not accepting donations.  The developers of CryptPad have not provided a donation URL. Please contact them directly if you insist on giving them money.

Cryptpad does take donations.  Please add the CryptPad donation link:https://opencollective.com/cryptpad/contribute

Also, is it possible to create a donation page for cryptpad wrapper? And then provide that link?

**Comment by PopsDoc** [comment]
Just watched a presentation.  They are 33% funded by grants that will run out at some point.  They'll need money.

**Comment by chrisguida** [comment]
Fixed by #16
