### ISSUE TITLE
Services Page -> Interfaces does not show Admin & checkup addresses

### ISSUE THREAD

**Issue by JesseMarkowitz** [chrisguida/cryptpad-wrapper#12]
The admin and checkup URLs (local and TOR) should be added to the interfaces page.

https://myserveraddress.local/checkup/
https://myserveraddress.local/admin/
https://myserveraddress.onion/checkup/
https://myserveraddress.onion/admin/

**Comment by chrisguida** [comment]
Let's put this in the properties page

**Comment by chrisguida** [comment]
Fixed by #16
