### ISSUE TITLE
Services Page -> instructions has Hello World text

### ISSUE THREAD

**Issue by JesseMarkowitz** [chrisguida/cryptpad-wrapper#14]
Instructions should not have place holder Hello World text.

Here are some draft instructions to consider using instead.

## Welcome to CryptPad
Collaboration and privacy - Yes, you can have both.

CryptPad provides a full-fledged office suite with all the tools necessary for productive collaboration including: Rich Text, Spreadsheets, Code/Markdown, Kanban, Slides, Whiteboard and Forms. 

Users can access this over TOR or Local, but not both at the same time.  TOR performance can be slow.  By default Local is selected, but you can change that on the config page.  After saving that change the service must be restarted to take effect.  NOTE: If you connected to your Embassy OS Server via TOR, when you click Launch UI it will use the TOR link to access CryptPad (regardless of this setting).  If you connected via local, Launch UI will use the local link to access CryptPad.

When you first connect to your self hosted CryptPad - Sign Up and create an account.  Then click on your name abbreviation in the upper right to bring up the account menu, click profile, view my profile, then copy public key.  Go back to the Embassy Service config page and paste that key as the Admin user public key.  This will allow you to access the CryptPad admin page.  There you can manage many more configurations - including preventing any new users from signing up.

We recommend visiting the [CryptPad documentation page](https://docs.cryptpad.org/en/) to learn more about using CryptPad.

**Comment by chrisguida** [comment]
Fixed by #16
