### ISSUE TITLE
[feat] make `/calendar` functionality known

### ISSUE THREAD

**Issue by MattDHill** [chrisguida/cryptpad-wrapper#20]
Currently, it is not apparent that you can go to `/calendar`. This could be added to instructions and/or added as a Property URL that can copy/pasted into the URL bar.

**Comment by MattDHill** [comment]
Turns out this is available through the GUI, just not as clear as it could be. Closing

**Comment by chrisguida** [comment]
location? in case people ask :)

**Comment by kn0wmad** [comment]
> location? in case people ask :)

Click on your profile picture in the top right - also shows Contacts.  No DAV support planned at this time, unfortunately.
