### ISSUE TITLE
Configuration page needs option to add user public signing key (to support web administration)

### ISSUE THREAD

**Issue by JesseMarkowitz** [chrisguida/cryptpad-wrapper#3]
Alpha testing should be able to include testing the web administration functionality. That functionality is enabled by adding a registered user's public signing key to the adminKeys array in cryptpad/config/config.js.   The wrapper should either allow a user to paste their key into the config, or create a new key and give the user access to it.

**Comment by chrisguida** [comment]
Fixed by 7e73648b0365ae6e189003d40923edbaf9323f87
