### ISSUE TITLE
Backup of CryptPad fails

### ISSUE THREAD

**Issue by JesseMarkowitz** [chrisguida/cryptpad-wrapper#5]
Environment - EOS 3.1.1, CryptPad 5.0.0, Chrome Version 104.0.5112.81 (Official Build) (64-bit) on Windows 10

When backing up CryptPad service get error message:
>cryptpad
>Failed: Backup Error: Could not create backup: No such file or directory (os error 2)

**Comment by chrisguida** [comment]
This will be super easy

**Comment by chrisguida** [comment]
This may be harder than I expected given that crytpad has 5 volumes

**Comment by chrisguida** [comment]
Fixed by #16
